version: '3'
services:
#   client:
#     build: ./client
#     ports:
#       - "3000:3000"
#       - "35729:35729"
#   node:
#     build: ./node
#     ports:
#       - "5001:5001"
  db:
    build: ./db
    ports:
      - "5432:5432"
  # nginx:
  #   build: ./nginx