version: '3'

services:
    client:
        container_name: client
        build: ./client
        volumes:
            - ./client/src:/client/src
            - ./client/public:/client/public
        ports:
            - "3000:3000"
        environment:
            REACT_APP_BASE_URL: http://127.0.0.1:3001

    server:
        container_name: server
        build: ./server
        volumes:
            - ./server/src:/server/src
        ports:
            - "3001:3001"
        # links:
        #     - db:db
        # depends_on:
        #     - db
        env_file: ./server/.env
        environment:
            PORT: 3001
            CONNECTION_STRING: "postgres://user:pass@db/postgres"
    
    db:
        container_name: db
        build: ./db
        volumes:
            - ./db/js:/db/js
            - ./db/sql:/db/sql
        env_file: ./db/.env
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
