import gql from 'graphql-tag';

export default {
    query: gql`query System($nodeId:ID!){
        system(nodeId:$nodeId){
            nodeId
            id
            name
            defaultGlassSize
            defaultGlassBite
            depth
            defaultSightline
            shimSize
            manufacturerByManufacturerId{
                nodeId
                id
                name
            }
            systemTypeBySystemTypeId{
                nodeId
                id
                type
                systemTypeDetailTypeConfigurationTypesBySystemTypeId{
                    nodes{
                        nodeId
                        mirrorable
                        required
                        presentationLevel
                        overrideLevel
                        systemTypeId
                        detailTypeId
                        detailTypeByDetailTypeId{
                            nodeId
                            id
                            type
                        }
                        configurationTypeId
                        configurationTypeByConfigurationTypeId{
                            nodeId
                            id
                            type
                            door
                        }
                        systemConfigurationOverridesBySystemTypeIdAndDetailTypeIdAndConfigurationTypeId{
                            nodes{
                                nodeId
                                mirrorableOverride
                                requiredOverride
                                presentationLevelOverride
                                overrideLevelOverride
                                systemId
                                systemTypeId
                                detailTypeId
                                configurationTypeId
                            }
                        }
                    }
                }
            }
            systemSystemTagsBySystemId{
                nodes{
                    nodeId
                    systemTagBySystemTagId{
                        nodeId
                        id
                        tag
                    }
                }
            }
            systemInfillSizesBySystemId{
                nodes{
                    nodeId
                    infillSize
                    infillSizeByInfillSize{
                        nodeId
                        size
                    }
                }
            }
            systemInfillPocketTypesBySystemId{
                nodes{
                    nodeId
                    infillPocketTypeByInfillPocketTypeId{
                        nodeId
                        id
                        type
                        captured
                        description
                    }
                }
            }
            systemInfillPocketSizesBySystemId{
                nodes{
                    nodeId
                    infillPocketSizeByInfillPocketSize{
                        nodeId
                        size
                    }
                }
            }
            invalidSystemConfigurationTypesBySystemId{
                nodes{
                    nodeId
                    systemId
                    invalidConfigurationTypeId
                    configurationTypeByInvalidConfigurationTypeId{
                        nodeId
                        id
                        type
                        door
                    }
                }
            }
            systemOptionsBySystemId {
                nodes {
                    nodeId
                    id
                    name
                    systemId
                    optionOrder
                    overrideLevel
                    presentationLevel
                    optionValuesBySystemOptionId {
                        nodes {
                            nodeId
                            id
                            name
                            value
                        }
                    }
                    systemOptionConfigurationTypesBySystemOptionId{
                        nodes{
                            nodeId
                            configurationTypeId
                            configurationTypeByConfigurationTypeId{
                                nodeId
                                id
                                type
                                door
                            }
                        }
                    }
                }
            }
            optionCombinationsBySystemId{
                nodes{
                    nodeId
                    id
                    invalid
                    optionCombinationConfigurationTypesByOptionCombinationId{
                        nodes{
                            nodeId
                            configurationTypeByConfigurationTypeId{
                                nodeId
                                id
                                type
                                door
                            }
                        }
                    }
                    optionCombinationOptionValuesByOptionCombinationId{
                        nodes{
                            nodeId
                            optionValueByOptionValueId{
                                nodeId
                                id
                                name
                                value
                                systemOptionBySystemOptionId{
                                    nodeId
                                    id
                                    name
                                }
                            }
                        }
                    }
                }
            }
        }
        allSystemTypes{
            nodes{
                nodeId
                id
                type
            }
        }
        allSystemTags{
            nodes{
                nodeId
                id
                tag
            }
        }
        allInfillSizes{
            nodes{
                nodeId
                size
            }
        }
        allInfillPocketTypes{
            nodes{
                nodeId
                id
                type
            }
        }
        allInfillPocketSizes{
            nodes{
                nodeId
                size
            }
        }
        allConfigurationTypes{
            nodes{
                nodeId
                id
                type
                door
            }
        }
    }`,
};