const CONTENT_TYPES = {
    GLASS: 'GLASS',
    VOID_INTERNAL: 'VOID_INTERNAL',
    VOID_LEFT_NOTCH: 'VOID_LEFT_NOTCH',
    VOID_RIGHT_NOTCH: 'VOID_RIGHT_NOTCH',
    VOID_RAISED_CURB: 'VOID_RAISED_CURB',
    VOID_STEPPED_HEAD: 'VOID_STEPPED_HEAD',
};

export default CONTENT_TYPES;