
SELECT * FROM update_entire_system(
    ROW(
        -- SYSTEM INFO
        -- id INTEGER,
        NULL,
        -- manufacturer_id INTEGER,
        1,
        -- system_type_id INTEGER,
        1,
        -- name VARCHAR(50),
        'Testing SQL Functions',
        -- depth FLOAT,
        NULL,
        -- default_glass_size FLOAT,
        NULL,
        -- default_glass_bite FLOAT,
        NULL,
        -- default_sightline FLOAT,
        NULL,
        -- top_gap FLOAT,
        NULL,
        -- bottom_gap FLOAT,
        NULL,
        -- side_gap FLOAT,
        NULL,
        -- meeting_stile_gap FLOAT,
        NULL,
        -- inset FLOAT,
        NULL,
        -- glass_gap FLOAT,
        NULL,
        -- shim_size FLOAT,
        NULL,
        -- front_inset BOOLEAN,
        NULL,
        -- system_tag_ids INTEGER[],
        ARRAY [1,2,3],
        -- system_tag_ids_to_delete INTEGER[],
        NULL,
        -- -- GLAZING INFO
        -- infill_sizes FLOAT[],
        ARRAY [1],
        -- infill_sizes_to_delete FLOAT[],
        NULL,
        -- infill_pocket_type_ids INTEGER[],
        ARRAY [1,2],
        -- infill_pocket_type_ids_to_delete INTEGER[],
        NULL,
        -- infill_pocket_sizes FLOAT[],
        ARRAY [1],
        -- infill_pocket_sizes_to_delete FLOAT[],
        NULL,
        -- -- VALID TYPES
        -- invalid_system_configuration_type_ids INTEGER[],
        NULL,
        -- invalid_system_configuration_type_ids_to_delete INTEGER[],
        NULL,
        -- configuration_overrides entire_system_configuration_override[],
        NULL,
        -- configuration_overrides_to_delete entire_system_configuration_override[],
        NULL,
        -- -- OPTIONS
        -- system_options entire_system_option[],
        NULL,
        -- system_option_ids_to_delete INTEGER[]
        NULL
    )::entire_system
);
