import gql from 'graphql-tag';

export default gql`{
    allSystemTypes{
        nodes{
            nodeId
            id
            type
            systemTypeDetailTypesBySystemTypeId{
                nodes{
                    nodeId
                    detailTypeByDetailTypeId{
                        nodeId
                        id
                        type
                        vertical
                        entrance
                    }
                }
            }
            systemTypeDetailTypeConfigurationTypesBySystemTypeId{
                nodes{
                    nodeId
                    required
                    mirrorable
                    detailTypeByDetailTypeId{
                        nodeId
                        id
                    }
                    configurationTypeByConfigurationTypeId{
                        nodeId
                        id
                        type
                        door
                        overrideLevel
                        presentationLevel
                    }
                }
            }
        }
    }
    allSystemTags{
        nodes{
            nodeId
            id
            type
        }
    }
}`;