
-- ROLES

DROP ROLE unauthorized;
DROP ROLE gc_client;
DROP ROLE gc_data_entry;
DROP ROLE gc_admin;

CREATE ROLE unauthorized NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE gc_client NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
CREATE ROLE gc_data_entry NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
CREATE ROLE gc_admin NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
