
SET search_path TO public, gc_utils, gc_public, gc_data, gc_protected, gc_controlled, gc_private;

-- INITIAL MANUFACTURER
INSERT INTO manufacturers (name) VALUES ('Kawneer');

-- INITIAL SYSTEM
INSERT INTO systems (name, manufacturer_id, system_type) VALUES ('Initial System', 1, 'STOREFRONT');

INSERT INTO system_options (name, system_id) VALUES('SET', 1);

INSERT INTO system_option_values (name, parent_system_option_path, child_type) VALUES
('CENTER', '1.SET', 'OPTION'),
('BACK', '1.SET', 'OPTION'),
('MULTI-PLANE', '1.SET', 'OPTION'),
('FRONT', '1.SET', 'OPTION');

INSERT INTO system_options (name, parent_system_option_value_path) VALUES('JOINERY', '1.SET.CENTER');

INSERT INTO system_option_values (name, parent_system_option_path, child_type) VALUES
('SCREW_SPLINE', '1.SET.CENTER.JOINERY', 'DETAIL'),
('SHEAR_BLOCK', '1.SET.CENTER.JOINERY', 'DETAIL'),
('STICK', '1.SET.CENTER.JOINERY', 'DETAIL');

INSERT INTO system_details (detail_type, parent_system_option_value_path) VALUES
('HEAD', '1.SET.CENTER.JOINERY.SCREW_SPLINE'),
('HORIZONTAL', '1.SET.CENTER.JOINERY.SCREW_SPLINE'),
('SILL', '1.SET.CENTER.JOINERY.SCREW_SPLINE');

INSERT INTO detail_options (name, parent_system_detail_path) VALUES('STOPS', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD');

INSERT INTO detail_option_values (name, parent_detail_option_path, child_type) VALUES
('UP', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.', 'CONFIGURATION'),
('DOWN', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.', 'CONFIGURATION');


INSERT INTO detail_options (name, parent_detail_option_value_path) VALUES('GLAZING', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN');

INSERT INTO detail_option_values (name, parent_detail_option_path, child_type) VALUES
('INSIDE', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING', 'CONFIGURATION'),
('OUTSIDE', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING', 'CONFIGURATION');

INSERT INTO system_configurations (configuration_type, parent_detail_option_value_path) VALUES
('HEAD', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.UP'),
('COMPENSATING_RECEPTOR', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.UP');
('HEAD', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.INSIDE'),
('COMPENSATING_RECEPTOR', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.INSIDE'),
('HEAD', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.OUTSIDE'),
('COMPENSATING_RECEPTOR', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.OUTSIDE');

INSERT INTO configuration_option_values (name, parent_configuration_type_path) VALUES
('DURABILITY', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.INSIDE.COMPENSATING_RECEPTOR'),
('DURABILITY', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.OUTSIDE.COMPENSATING_RECEPTOR'),
('DURABILITY', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.UP.COMPENSATING_RECEPTOR');

INSERT INTO configuration_option_values (name, parent_configuration_option_path) VALUES
('STANDARD_DUTY', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.INSIDE.COMPENSATING_RECEPTOR.DURABILITY'),
('HIGH_PERFORMANCE', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.INSIDE.COMPENSATING_RECEPTOR.DURABILITY'),
('STANDARD_DUTY', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.OUTSIDE.COMPENSATING_RECEPTOR.DURABILITY'),
('HIGH_PERFORMANCE', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.DOWN.GLAZING.OUTSIDE.COMPENSATING_RECEPTOR.DURABILITY'),
('STANDARD_DUTY', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.UP.COMPENSATING_RECEPTOR.DURABILITY'),
('HIGH_PERFORMANCE', '1.SET.CENTER.JOINERY.SCREW_SPLINE.HEAD.STOPS.UP.COMPENSATING_RECEPTOR.DURABILITY');

-- TEST SYSTEM
INSERT INTO systems (name, manufacturer_id, system_type)
VALUES ('Test System', 1, 'STOREFRONT');

-- PROJECT FOR USER_ONE
INSERT INTO projects (name, owner_id) VALUES ('Demo Project', 1);

-- TEST PROJECT
INSERT INTO projects (name, owner_id) VALUES ('Test Project', 2);

-- -- TEST SYSTEM SET
-- INSERT INTO system_sets (project_id, system_id, system_option_value_id, name) VALUES
-- (2, 1, 5, 'Initial System Set');
