import { sampleSystemMap2 } from "../sample-systems";
import getAllEndNodes from "../../system/get-all-end-nodes";

function testGetAllEndNodes({
    payload: {
        path,
        systemMap,
    },
    expected,
}) {
    const result = getAllEndNodes({ path }, systemMap);
    test(`getting all end nodes of path: ${path}`, () => {
        expected.forEach(nodePath => {
            expect(result).toContainEqual(expect.objectContaining({ path: nodePath }));
        });
    });
};

testGetAllEndNodes({
    payload: {
        path: '2',
        systemMap: sampleSystemMap2,
    },
    expected: [
        '2.SET.BACK.__DT__.HEAD',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.COMPENSATING_RECEPTOR.DURABILITY.HIGH_PERFORMANCE.__PT14__.451_VG_572',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.COMPENSATING_RECEPTOR.DURABILITY.HIGH_PERFORMANCE.__PT15__.451T_VG_570',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.COMPENSATING_RECEPTOR.DURABILITY.STANDARD_DUTY',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.HEAD.STOPS.DOWN.GLAZING.INSIDE.__PT12__.451T_CG_003',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.HEAD.STOPS.DOWN.GLAZING.INSIDE.__PT13__.451_CG_004',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.HEAD.STOPS.DOWN.GLAZING.OUTSIDE.__PT10__.451T_CG_003',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.HEAD.STOPS.DOWN.GLAZING.OUTSIDE.__PT11__.451_CG_004',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.HEAD.STOPS.UP.__PT9__.451T_CG_001',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HEAD.__CT__.SHIM_SUPPORT.__PT16__.451T_026',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.DOWN.GLAZING.INSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.DOWN.GLAZING.OUTSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.UP.GLAZING.INSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.UP.GLAZING.OUTSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.DOWN.__CT__.SHIM_SUPPORT',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.DOWN.__CT__.SILL',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.DOWN.__CT__.SILL_FLASHING',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.UP.GLAZING.INSIDE.__CT__.SHIM_SUPPORT',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.UP.GLAZING.INSIDE.__CT__.SILL',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.UP.GLAZING.OUTSIDE.__CT__.SHIM_SUPPORT',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.UP.GLAZING.OUTSIDE.__CT__.SILL',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.SILL.STOPS.UP.GLAZING.OUTSIDE.__CT__.SILL_FLASHING',
        '2.SET.CENTER.JOINERY.SHEAR_BLOCK.__DT__.HEAD',
        '2.SET.CENTER.JOINERY.STICK.__DT__.HEAD',
        '2.SET.FRONT.__DT__.HEAD',
    ]
});

testGetAllEndNodes({
    payload: {
        path: '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL',
        systemMap: sampleSystemMap2,
    },
    expected: [
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.DOWN.GLAZING.INSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.DOWN.GLAZING.OUTSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.UP.GLAZING.INSIDE',
        '2.SET.CENTER.JOINERY.SCREW_SPLINE.__DT__.HORIZONTAL.__CT__.HORIZONTAL.STOPS.UP.GLAZING.OUTSIDE',
    ]
})