import { cacheExchange } from '@urql/exchange-graphcache';
import { Client, debugExchange, dedupExchange, fetchExchange } from 'urql';
import { map, pipe } from 'wonka';
import { getAuthorization } from './local-storage';
// schema automatically generated by postgraphile
import { data as schema } from './schemas/_schema.json';
import { normalizeQueryResponse } from './utils/index.js';

export default new Client({
    url: `${process.env.REACT_APP_BASE_URL}/graphql`,
    schema,
    fetchOptions: () => ({
        headers: {
            authorization: getAuthorization(),
        },
    }),
    exchanges: [
        dedupExchange,
        debugExchange,
        ({ forward }) => ops$ => pipe(
            ops$,
            forward,
            map(operation => ({
                ...operation,
                data: normalizeQueryResponse(operation),
            })),
        ),
        cacheExchange({}),
        fetchExchange,
    ],
});
